# file paths
development:
  proceed:
    file:
      xyChina: C:/Users/DELL/Desktop/20170318/N2017-03-06.xls
      newTemplate: C:/Users/DELL/Desktop/20170318/N20170313.xls
      oldTemplate: C:/Users/DELL/Desktop/20170318/O201703131.xls
      onlyToBase: