# file paths
development:
  proceed:
    file:
      xyChina: C:/Users/DELL/Desktop/20170523/N2017-05-15.xls
      newTemplate: C:/Users/DELL/Desktop/20170523/N20170522.xls
      oldTemplate: C:/Users/DELL/Desktop/20170523/O20170522.xls
      onlyToBase: