# file paths
development:
  proceed:
    file:
      xyChina: /Users/neo/Downloads/20170307/N2017-02-27.xls
      newTemplate: /Users/neo/Downloads/20170307/N0306.xls
      oldTemplate: /Users/neo/Downloads/20170307/O0306.xls
      onlyToBase: