# file paths
development:
  proceed:
    file:
        xyChina: /Users/neo/downloads/20170629/whcic170629.xls
#      xyChina: C:\Users\DELL\Desktop\20170623/whcic170623.xls
        newTemplate: /Users/neo/downloads/20170627/N20170626.xls
#      newTemplate: C:\Users\DELL\Desktop\20170619/N20170619.xls
        oldTemplate: /Users/neo/downloads/20170627/O20170626.xls
#      oldTemplate: C:\Users\DELL\Desktop\20170619/O20170619.xls
        onlyToBase: