# file paths
development:
  proceed:
    file:
      xyChina: /Users/neo/Downloads/20170118/N2017-01-11.xls
      newTemplate: /Users/neo/Downloads/20170118/N0116.xls
      oldTemplate: /Users/neo/Downloads/20170118/O0116.xls
      onlyToBase: