# file paths
development:
  proceed:
    file:
      xyChina: /Users/neo/downloads/20170605/N2017-06-01.xls
      newTemplate: /Users/neo/downloads/20170601/N20170531.xls
      oldTemplate: /Users/neo/downloads/20170601/O20170531.xls
      onlyToBase: