# file paths
development:
  proceed:
    file:
      xyChina: C:/Users/DELL/Desktop/20170421/N2017-04-10.xls
      newTemplate: C:/Users/DELL/Desktop/20170421/N20170417.xls
      oldTemplate: C:/Users/DELL/Desktop/20170421/O20170417.xls
      onlyToBase: