# file paths
development:
  proceed:
    file:
      xyChina: C:/Users/DELL/Desktop/20170401/N2017-03-22.xls
      newTemplate: C:/Users/DELL/Desktop/20170401/N201703271.xls
      oldTemplate: C:/Users/DELL/Desktop/20170401/O201703271.xls
      onlyToBase: